import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Providers } from "@/components/Providers";
import { UserMenu } from "@/components/UserMenu";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <Providers>
          <header className="sticky top-0 z-50 border-b border-border bg-surface/90 backdrop-blur">
            <div className="container mx-auto px-4 h-16 max-w-6xl flex items-center justify-between">
              <Link href="/" className="text-xl font-bold text-primary">
                Event Planner
              </Link>

              <nav className="flex items-center gap-4">
                <Link href="/dashboard" className="text-amber-50 hover:text-foreground transition-colors">
                  Dashboard
                </Link>

                <UserMenu />
              </nav>
            </div>
          </header>

          <main className="mx-auto flex w-full max-w-6xl flex-col px-4 py-8">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
